name: Terraform Plan
run-name: ${{ github.actor }} Terraform Plan
on: [push]
jobs:
  TerraformPlan:
    runs-on: ubuntu-latest
    environment: nonprod
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: terraform
        working-directory: ./terraform
        run: |
          terraform init ${{ secrets.BACKEND_CONFIG }}
          terraform plan \
            -var-file "${{ vars.VAR_FILE }}" \
            -var "role_arn=${{ secrets.ROLE_ARN }}"
