name: Terraform Plan PR
run-name: ${{ github.actor }} Terraform PR Plan
on:
  pull_request:
    branches:
      - main

jobs:
  TerraformPlan:
    runs-on: ubuntu-latest
    environment: nonprod
    permissions:
      pull-requests: write
    outputs:
      plan: ${{ steps.plan.env.plan }}
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Init
        working-directory: ./terraform
        run: terraform init ${{ secrets.BACKEND_CONFIG }}

      - name: Plan
        id: plan
        working-directory: ./terraform
        run: |
          terraform plan -var-file="${{ vars.VAR_FILE }}" -var="role_arn=${{ secrets.ROLE_ARN }}"
          echo "PLAN<<EOF" >> $GITHUB_ENV
          terraform plan -no-color -var-file="${{ vars.VAR_FILE }}" -var="role_arn=${{ secrets.ROLE_ARN }}" | grep "Plan:\|# " | grep -v "(\|)" >> $GITHUB_ENV 
          echo "EOF" >> $GITHUB_ENV

      - name: Comment PR
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## Terraform Plan: \n ```${{ env.PLAN }}````
            })
